### ISSUE TITLE
Add possibility to copy only on start

### ISSUE THREAD

**Issue by vladshcherbin** [sakitam-fdd/rollup-plugin-copied#3]
It would be nice to have an option to copy on start or on write. It's useful in watch mode when you don't want to copy files every time you bundle changes. The option can be named watch or smth.

**Comment by sakitam-fdd** [comment]
Good idea , now I have added a parameter to solve this problem, when set to false, only the changes of the first resource are monitored, and the monitoring is not repeated. Thank for your issues.

**Comment by vladshcherbin** [comment]
@sakitam-fdd nice, thank you 😉
